name: 'Setup mirrord e2e environment'
description: 'Install all required dependencies for mirrord e2e tests'
runs:
  using: "composite"
  steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: npm install express
      shell: bash
    - uses: actions/setup-python@v3
    - run: pip3 install flask fastapi uvicorn[standard]
      shell: bash
    - uses: actions/setup-go@v3
      with:
        go-version: "1.18.0"
    - run: |
        go version
      shell: bash
    - run: | # Build Go test apps.
        ./scripts/build_go_apps.sh 18
      shell: bash
    - uses: actions/setup-go@v3
      with:
        go-version: "1.19.0"
    - run: |
        go version
      shell: bash
    - run: | # Build Go test apps.
        ./scripts/build_go_apps.sh 19
      shell: bash
    - uses: actions/setup-go@v3
      with:
        go-version: "1.20.0-rc.3"
    - run: |
        go version
      shell: bash
    - run: | # Build Go test apps.
        ./scripts/build_go_apps.sh 20
      shell: bash
    - run: |
        cd tests/rust-e2e-fileops
        cargo build
      shell: bash
    - run: |
        cd tests/rust-unix-socket-client
        cargo build
      shell: bash
    - run: |
        cd tests/rust-bypassed-unix-socket
        cargo build
      shell: bash