name: Release docs base image
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Docker tags
        uses: ./.github/actions/set-image-tags
        id: set-tags
        with:
          base-name: ci-docs-build
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docs-build/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.set-tags.outputs.tags }}
